spring.application.name=convertCurrency

#Client API Config
freeCurrency.api.base.url= https://api.freecurrencyapi.com/v1/latest
freeCurrency.api.APIKey=fca_live_fAvbyCRajT8Vawbiy3ivVT7y9gdvJbcDNBO7Dgjs

#Logging Config
logging.level.root = debug
#logging.file.name=application.log
logging.config=classpath:logback-spring.xml